name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-11 libsdl2-dev libzmq3-dev libnode-dev
          dpkg -l | grep libnode

      - name: Set GCC to g++-11
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
          g++ --version

      - name: Build project
        run: make
